# fly.toml app configuration file generated for edu-ai-api on 2024-11-13T15:31:18-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'edu-ai-api'
primary_region = 'iad'

[build]
  [build.args]
    GO_VERSION = '1.22.6'

[env]
  PORT = '3000'
  AUTH0_DOMAIN = 'edu-ai.us.auth0.com'
  AUTH0_AUDIENCE = 'https://localhost:3000'
  API_URL = 'https://edu-ai.fly.dev'
  ENV = 'server'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
